CREATE DATABASE KISHOR_BANKAR;
USE KISHOR_BANKAR;
SELECT * FROM WORLD_POPULATION_DATA_3;

-- 1. EXTRACT THE WORLD  POPULATION OF 2023
SELECT 
    SUM(POPULATION_2023)
FROM
    WORLD_POPULATION_DATA_3;
    
    
-- 2. EXTRACT THE WORLD POPULATION GROWTH FROM 2000 TILL  THE LATEST CENSUS(2023)
SELECT 
    SUM(POPULATION_2023) - SUM(POPULATION_2000) AS WORLD_POPULATION_GROWTH
FROM
    WORLD_POPULATION_DATA_3;
    
    
-- 3. EXTRACT CONTINENTWISE POPULATION IN 2023

SELECT 
    CONTINENT, SUM(POPULATION_2023) AS POPULATION_2023
FROM
    WORLD_POPULATION_DATA_3
GROUP BY CONTINENT
ORDER BY CONTINENT ASC;


-- 4. EXTRACT THE  ASIA'S TOP 5 HIGHEST POPULATED COUNTRIES
SELECT 
    COUNTRY, SUM(POPULATION_2023)
FROM
    WORLD_POPULATION_DATA_3
WHERE
    CONTINENT = 'ASIA'
GROUP BY COUNTRY
ORDER BY CONTINENT ASC
LIMIT 5;

-- 5. HOW HAS INDIA'S POPULATION GROWN SINCE 1970  BASED ON EVERY CENSUS

SELECT 
    country,
    (population_2020 - population_2010) AS '10-20  growth',
    (population_2010 - population_2000) AS '00-10 growth',
    (POPULATION_2000 - POPULATION_1990) AS '90 -00 growth',
    (POPULATION_1990 - POPULATION_1980) AS '80-90 growth',
    (POPULATION_1980 - POPULATION_1970) AS '70-80 growth'
FROM
    world_population_data_3
WHERE
    COUNTRY = 'India';

-- 6.  PROVIDE THE 5 HIGHEST POPULATED COUNTRIES IN EACH CONTINENT

SELECT T.* FROM 
(SELECT DENSE_RANK() OVER (PARTITION BY CONTINENT ORDER BY POPULATION_2023 DESC) AS 
CONTINENT_RANK , CONTINENT, COUNTRY, POPULATION_2023,WORLD_PERCENTAGE FROM WORLD_POPULATION_DATA_3 )AS T 
WHERE T.CONTINENT_RANK <=5;



-- 7.  10 COUINTRIES WITH LEAST POPULATION IN 2023 YEAR

SELECT DENSE_RANK() OVER (ORDER BY POPULATION_2023 ASC )AS DENSE_RANK_, CONTINENT , POPULATION_2023 
FROM WORLD_POPULATION_DATA_3 
ORDER BY POPULATION_2023 ASC LIMIT 10;


 -- 8 .  PROVIDE THE GROWTH RATE OF COUNTRIES  FROM 1970 TO 2023 IN MILLIONS

SELECT 
    Continent,
    Country,
    (Population_2020 - Population_1970) / 1000000 AS growth_50years_IN_MILLIONS
FROM
    world_population_data_3;

 
